services:
  web:
    build: .
    command: gunicorn issfwr.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/code
      - static_volume:/code/staticfiles
    expose:
      - 8000
    env_file:
      - .env.dev
    depends_on:
      - db
  db:
    image: postgres:16-bullseye
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env.dev
  nginx:
    image: nginx:latest
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./certs:/etc/nginx/certs
      - static_volume:/usr/share/nginx/html
    depends_on:
      - web

volumes:
  postgres_data:
  static_volume:
