[tool.black]
target-version = ['py311']
line-length = 100

[tool.isort]
profile = 'black'
line_length = 100

[tool.mypy]
plugins = ["mypy_django_plugin.main"]

[tool.django-stubs]
django_settings_module = "world_rankings.settings"

[tool.pytest.ini_options]
DJANGO_SETTINGS_MODULE = "world_rankings.settings"
python_files = ["test_*.py", "*_test.py", "testing/python/*.py"]
